apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80      # The port that the service will expose
    targetPort: 80 # The port the container is exposing
  type: LoadBalancer  # Use LoadBalancer to expose externally (on GKE, AWS, etc.)
